tier4/autoware_lanelet2_map_validator

- .github/workflows/build-and-test-differential.yaml
This PR have changed `build-and-test-differential` so that it doesn't pass when the `tag:run-build-and-test-differential` label is not set.
None.
None.
> ci: change build-and-test-differential algorithm

- .github/workflows/build-and-test-differential.yaml
I was customizing `build-and-test-differential.yaml` in order to not run the job `build-and-test-differential` when the source code is not changed but it seems it is not working as expected (like the figure below).
I've changed the algorithm again and I finally it should work as expected.
I tried cases below in https://github.com/tier4/autoware_lanelet2_map_validator/pull/10 and seems to work fine
- Only documents have changed
- Code changes with no bugs
- Code changes with a bug
I had to remove required status to merge this for a while.
None.
> ci: removed check-directory-changes and added summarize-jobs

- autoware_lanelet2_map_validator/src/common/validation.cpp
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validation.hpp
- autoware_lanelet2_map_validator/src/main.cpp
This re-factorization is aimed to extract validation issues to the main process, and declare the visualization in the main process.  This is because there are future plans to use the validation issues in other kinds of tasks, in addition, it is difficult to reflect loading/parsing issues to the output with the current system.
The main changes are
- Changed confusing names
- Function `process_requirements` to `validate_all_requirements`
- Variable `map_issue` to `loading_issues`
- Bring the visualization process `summarize_validator_results` to main
- Extract the JSON exportation process as `export_results`.
- There was a code
```cpp
if (!lanelet_map_ptr) {
lanelet::validation::printAllIssues(map_issue);
}
```
but detecting a loading issue doesn't mean `lanelet_map_ptr` to be nullptr. (It …
> refactor: extract mapping_issues to main

- autoware_lanelet2_map_validator/CHANGELOG.rst
- autoware_lanelet2_map_validator/package.xml
This PR bumps the version of autoware_lanelet2_map_validator to 1.1.0.
I'll create a new release and tag after this PR is merged.
None.
None.
None.
> chore: bump version to 1.1.0

- autoware_lanelet2_map_validator/autoware_requirement_set.json
- autoware_lanelet2_map_validator/docs/traffic_light/light_bulb_tagging.md
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validators/traffic_light/light_bulb_tagging.hpp
- autoware_lanelet2_map_validator/src/validators/traffic_light/light_bulb_tagging.cpp
- autoware_lanelet2_map_validator/template/test_validator_template.cpp
- autoware_lanelet2_map_validator/template/validator_template.cpp
- autoware_lanelet2_map_validator/template/validator_template.hpp
- autoware_lanelet2_map_validator/template/validator_template.md
- autoware_lanelet2_map_validator/test/data/map/traffic_light/traffic_light_with_arrow_bulb.osm
- autoware_lanelet2_map_validator/test/data/map/traffic_light/traffic_light_with_colorless_arrow_bulb.osm
- autoware_lanelet2_map_validator/test/data/map/traffic_light/traffic_light_with_invalid_arrow_direction.osm
- autoware_lanelet2_map_validator/test/data/map/traffic_light/traffic_light_with_invalid_color.osm
- autoware_lanelet2_map_validator/test/src/traffic_light/test_light_bulb_tagging.cpp
This PR adds a validator `mapping.traffic_light.light_bulb_tagging` that does the checks the following (according to map requirement vm-04-03)
- Each light bulb has a `color` tag set
- Each light bulb has a valid `color` (red, yellow, or green)
- If a light bulb has a `arrow` tag check whether it is valid (up, right, left, up_right or up_left)
I've also added `mapping.traffic_light.light_bulb_tagging` to `autoware_requirement_set.json`
Besides, since the template codes were old and mistaken, I've also fixed them. Excuse me for including them in this PR.
- Check that `colcon test` works with no errors
- Checked that `ros2 run` with new defected test maps cause issues as intended
- Checked that normal usages works well as intended.
Since this validator depends on correct regulatory element …
> feat: check light bulb attributes

- autoware_lanelet2_map_validator/CHANGELOG.rst
- autoware_lanelet2_map_validator/package.xml
This PR bumps the version to 1.2.0
`colcon test` has passed.
None.
None.
> chore: bump version to 1.2.0

- autoware_lanelet2_map_validator/CHANGELOG.rst
- autoware_lanelet2_map_validator/package.xml
This PR bumps the version of autoware_lanelet2_map_validator to 1.3.0
None
None.
None.
> chore: bump to version 1.3.0

- autoware_lanelet2_map_validator/src/common/io.cpp
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/io.hpp
- autoware_lanelet2_map_validator/src/main.cpp
This PR adds a `validation_info` block to the output `lanelet2_validation_results.json` file to benefit external tools that they can get the information what kind of validation was done.
The validation_info block will look like this.
```json
"validation_info": {
"map_requirements": {
"filename": "common.json",
"version": "1.0.2"
},
"target_map": "komatsu/lanelet2_map.osm",
"validator": {
"name": "autoware_lanelet2_map_validator",
"version": "1.3.0"
}
}
```
It adds the information of...
- Map file name and its parent directory
- File name of map_requirements
- Version of the map_requirements
- Name of this tool (= autoware_lanelet2_map_validator)
- Version of autoware_lanelet2_map_validator
Checked that usual usage has be done as intended.
Confirmed that colcon test passes.
None.
A new …
> feat: add validation_info to the lanelet2_validation_results.json

- README.md
- README_ja.md
- autoware_lanelet2_map_validator/CMakeLists.txt
- autoware_lanelet2_map_validator/config/params.yaml
- autoware_lanelet2_map_validator/docs/how_to_contribute.md
- autoware_lanelet2_map_validator/docs/lane/border_sharing.md
- autoware_lanelet2_map_validator/package.xml
- autoware_lanelet2_map_validator/src/common/cli.cpp
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/cli.hpp
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/config_store.hpp
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validators/lane/border_sharing.hpp
- autoware_lanelet2_map_validator/src/main.cpp
- autoware_lanelet2_map_validator/src/validators/lane/border_sharing.cpp
- autoware_lanelet2_map_validator/template/validator_template.md
- autoware_lanelet2_map_validator/test/src/include/map_validation_tester.hpp
- autoware_lanelet2_map_validator/test/src/test_parameter_loading.cpp
- autoware_lanelet2_map_validator/test/src/traffic_light/test_regulatory_elements_details_for_traffic_lights.cpp
This is a rework of https://github.com/tier4/autoware_lanelet2_map_validator/pull/35.
This PR adds a parameter loader class `ValidatorConfigStore` to the autoware_lanelet2_map_validator.
This class will read parameters from the `config/params.yaml` file at first of the validation, and then validators can retrieve their parameters by `ValidatorConfigStore::parameters()`.
While the previous PR (https://github.com/tier4/autoware_lanelet2_map_validator/pull/35) cannot get parameters from external files, this PR can.
Since the current autoware_lanelet2_map_validator doesn't have validator that needs parameters, I set the threshold of IoU in the `mapping.lane.border_sharing` as a parameter for demonstration.
Hence, this PR does the following.
1. Adds a new class `ValidatorConfigStore`
2. Adds a …
> feat: create ValidatorConfigStore to read parameters

- autoware_lanelet2_map_validator/docs/intersection/regulatory_element_details_for_virtual_traffic_lights.md
- autoware_lanelet2_map_validator/map_requirements/autoware_requirement_set.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2024_2_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2024_7_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/common.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/delivery_robot-v2023_10_2.json
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validators/intersection/regulatory_element_details_for_virtual_traffic_lights.hpp
- autoware_lanelet2_map_validator/src/validators/intersection/regulatory_element_details_for_virtual_traffic_lights.cpp
- autoware_lanelet2_map_validator/test/data/map/intersection/correct_virtual_traffic_light.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_missing_end_line.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_missing_ref_line.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_missing_refers.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_missing_start_line.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_with_multiple_ref_lines.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_with_multiple_start_lines.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_with_wrong_end_line_type.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_with_wrong_ref_line_type.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_with_wrong_refers_type.osm
- autoware_lanelet2_map_validator/test/data/map/intersection/virtual_traffic_light_with_wrong_start_line_type.osm
- autoware_lanelet2_map_validator/test/data/map/sample_map.osm
- autoware_lanelet2_map_validator/test/src/intersection/test_regulatory_element_details_for_virtual_traffic_lights.cpp
This PR adds a validator "mapping.intersection.regulatory_element_details_for_virtual_traffic_lights" that checks the details of `virtual_traffic_light` type regulatory elements. 
[Regulatory Element Definition (Japanese Link)](https://docs.pilot.auto/reference-design/common/map-requirements/vector-map-requirements/category_intersection/#vm-03-16-%E4%BA%A4%E5%B7%AE%E7%82%B9%E8%AA%BF%E5%81%9C%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E4%BB%AE%E6%83%B3%E4%BF%A1%E5%8F%B7%E6%A9%9F)
In detail, this PR contains the following.
- The main implementation
- regulatory_element_details_for_virtual_traffic_lights.hpp
- regulatory_element_details_for_virtual_traffic_lights.cpp
- Test code and test maps
- test_regulatory_element_details_for_virtual_traffic_lights.cpp
- ***.osm files
- I've added a virtual …
> feat: check the details of regulatory elements for virtual traffic lights

- autoware_lanelet2_map_validator/map_requirements/autoware_requirement_set.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2024_2_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2024_7_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2025_3_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/common.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/delivery_robot-v2023_10_2.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/cargo_transport-v2024_2_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/cargo_transport-v2024_7_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/common.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/delivery_robot-v2023_10_2.json
Fix name mistakes about mapping.intersection.virtual_traffic_light_line_order, and add mapping.intersection.virtual_traffic_light_line_order to archived verisons
Checked that normal use `ros2 run ...` works well
Excuse me for bypass merging this.
None.
> fix: fix name mistakes about mapping.intersection.virtual_traffic_light_line_order

- autoware_lanelet2_map_validator/CHANGELOG.rst
- autoware_lanelet2_map_validator/package.xml
This PR bumps the version of autoware_lanelet2_map_validator to 1.4.0
1. Checked that `colcon test` works
2. Checked that normal usage `ros2 run ...` works.
Excuse me for bypass merging this.
None.
> chore: bump version to 1.4.0

- autoware_lanelet2_map_validator/CHANGELOG.rst
- autoware_lanelet2_map_validator/package.xml
This PR bumps the patch version to 1.4.1
Since I've added a fix commit, I'll bump the patch version
I will bypass merge this PR.
None.
> chore: bump version to 1.4.1

- .github/workflows/build-and-test-differential.yaml
- .github/workflows/build-and-test.yaml
- autoware_lanelet2_map_validator/src/main.cpp
Actually Autoware doesn't support the `latest-prebuild` image.
https://github.com/orgs/autowarefoundation/discussions/4995
This PR changes the container from `latest-prebuilt` to ~~`universe-devel`~~ `core-devel`.
This PR contains a dummy line to the `main.cpp` to test the workflow, so we have to revert it after we check the change works fine.
None.
> ci: quit using autoware:latest-prebuilt

- autoware_lanelet2_map_validator/docs/intersection/intersection_area_validity.md
- autoware_lanelet2_map_validator/src/validators/intersection/intersection_area_validity.cpp
- autoware_lanelet2_map_validator/test/src/intersection/test_intersection_area_validity.cpp
This PR fixes `mapping.intersection.intersection_area_validity` so that "wrong orientation" error of polygons will be ignored.
Hence, this PR does the following
- Do not create issues when the `is_valid` is false but is actually a "wrong orientation" issue.
- Change the test of "wrong orientation" map and check that no issues will be detected.
- Add about this change in the documentation.
- Check that "wrong orientation" related message do not appear when I `ros2 run autoware_lanelet2_map_validator autoware_lanelet2_map_validator` to any map.
- Check that `colcon test` passes.
None.
None.
> fix: do not count wrong polygon orientation as an issue

- autoware_lanelet2_map_validator/docs/how_to_contribute.md
Remove the section "5. Increase version" from `how_to_contribute.md` since we are not managing versions like this anymore.
**I'll bypass merge this one**
None.
> docs: remove the update version section from the how_to_contribute.md

- autoware_lanelet2_map_validator/config/issues_info.json
- autoware_lanelet2_map_validator/docs/intersection/intersection_lanelet_border_type.md
- autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validators/intersection/intersection_lanelet_border_type.hpp
- autoware_lanelet2_map_validator/src/validators/intersection/intersection_lanelet_border_type.cpp
- autoware_lanelet2_map_validator/test/data/map/intersection/intersection_lanelet_invalid_border_type.osm
- autoware_lanelet2_map_validator/test/data/map/sample_map.osm
- autoware_lanelet2_map_validator/test/src/intersection/test_intersection_lanelet_border_type.cpp
This PR introduces a new validator: `mapping.intersection.lanelet_border_type`.
Its purpose is to ensure that lanelets tagged with `intersection_area` have both LeftBound and RightBound of type `"virtual"` or `"road_border"` as required by [VM-03-02 specification](https://docs.pilot.auto/en/reference-design/common/map-requirements/vector-map-requirements/category_intersection/#vm-03-02-lanelets-turn-direction-and-virtual).
Lanelets that have the `intersection_area` tag
* Whether the `LeftBound` and `RightBound` of the lanelet are of type `"virtual"` or `"road_border"`
* `autoware_lanelet2_map_validator/include/lanelet2_map_validator/validators/intersection/intersection_lanelet_border_type.hpp`
* `autoware_lanelet2_map_validator/src/validators/intersection/intersection_lanelet_border_type.c …
> feat(intersection): added validator for Lanelet's turn direction and virtual (vm-03-02)

- autoware_lanelet2_map_validator/map_requirements/autoware_requirement_set.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2024_2_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2024_7_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/cargo_transport-v2025_3_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/common.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/delivery_robot-v2023_10_2.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/robo_taxi-v0_44_0_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/robo_taxi-v0_45_0_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/robo_taxi-v0_46_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/robo_taxi-v0_47_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/robo_taxi-v0_48_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/shuttle_bus-v2_3_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/shuttle_bus-v3_0_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/shuttle_bus-v3_1_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/shuttle_bus-v4_0_1.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/shuttle_bus-v4_1_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/cargo_transport-v2024_2_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/cargo_transport-v2024_7_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/common.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/delivery_robot-v2023_10_2.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/robo_taxi-v0_44_0_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/robo_taxi-v0_45_0_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/robo_taxi-v0_46_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/robo_taxi-v0_47_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/shuttle_bus-v2_3_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/shuttle_bus-v3_0_0.json
- autoware_lanelet2_map_validator/map_requirements/pilot-auto/v1.0.2/shuttle_bus-v3_1_0.json
- autoware_lanelet2_map_validator/src/validators/intersection/virtual_traffic_light_line_order.cpp
This PR removes unnecessary `prerequisites` from map requirements.
We can classify two types of prerequisites
- A constraint to a complicated validator so that it will not crash when the prerequisite is not met.
- A guarantee that the latter validator also has a comprehensiveness of primitives to be checked. (e. g. If a traffic light regulatory element is missing, we cannot say that all traffic lights are perfect even if the latter validators succeeded)
However, the second role `prerequisites` hold was quite unuseful so I decided to delete this.
I've checked that prerequisites removed here doesn't crashes the latter validation that validators have enough exception handling. (but I added one to virtual_traffic_light_line_order.cpp)
Tested that `autoware_lanelet2_map_validator` doesn't …
> chore: remove unnecessary prerequisites from map requirements

- autoware_lanelet2_map_validator/src/validators/intersection/intersection_area_tagging.cpp
- autoware_lanelet2_map_validator/src/validators/traffic_light/regulatory_element_details_for_traffic_lights.cpp
I found that `regulatory_element_details_for_traffic_lights` and `intersection_area_tagging` doesn't have error handling when crosswalk lanelets involve. This PR fixes it.
Tested that real map validation will not output false negative errors.
Tested that `colcon test` passes.
**I'll bypass merge all the necessary changes to `feat/v1.5.0/the_grand_finale` first and then request for reviews.**
None.
> fix: ignore crosswalks for some validators

- autoware_lanelet2_map_validator/package.xml
We need this fix since the gui.py depends to autoware_lanelet2_extension_python and `gui.py` cannot be run without it.
Created a brand new Autoware workspace and checked that autoware_lanelet2_extension_python will be build together by `colcon build --packages-up-to` and the `gui.py` works without errors.
**I'll bypass merge this one**.
None.
> fix: add autoware_lanelet2_extension_python as dependency
